### ISSUE TITLE
Support for Cultivars and ICNCP naming

### ISSUE THREAD

**Issue by havardo** [gnames/gnparser#148]
Hi, 
Cultivars, and I suppose the [ICNCP](https://en.wikipedia.org/wiki/International_Code_of_Nomenclature_for_Cultivated_Plants) in general, appear not to be recognized by the parser. Is that something you might consider adding support for?

**Comment by dimus** [comment]
Support for cultivars and viruses in on a priority list, so it should happen eventually

**Comment by havardo** [comment]
Ok, good news that you have it on the road map at least. Thanks for the update.

**Comment by dimus** [comment]
Closing, because of all the great job done by @tobymarsden introduced a decent support for cultivars
