### ISSUE TITLE
Use Case Query - can using GN parser improve my name parsing and matching workflow?

### ISSUE THREAD

**Issue by debpaul** [gnames/gnparser#168]
**Use Case:** as a user shared, "right now I am downloading names from IRMING and GBIF, parsing taxon types I don’t need for my collection, and using SQL queries to match Genera. Need an easier method (and get better species matches)."

**Question:** For this user's workflow, would accessing GN services be "easier" and help with the matching?
**Question:** What would the workflow be?

**Comment by dimus** [comment]
I am not sure I understood the workflow.

- There are name-strings in an SQL database (Generic, Species, infraspecies?)
- There is a list of names from GBIF+IRMNG (Geneic, Species, Infraspecies?)
- The names are compared using full strings via SQL queries?

GNparser can help if  there is a comparison is between "full" names with authorship and such. Parsing both checklists and comparing "Stemmed Canonical Forms" from them would give the most forgiving matching. Comparing "Simple Canonical Forms" would not match names like "Betula verrucosa" and "Betula verrucosus". Comparing "Full Canonical Forms" would not match names like "Abies procera f. prostrata (Hornibr. ex Chitt.) Rehder" and "Abies procera prostrata (Hornibr. ex Chitt.) Rehder".

**Comment by debpaul** [comment]
This Use Case comes from Roger Burkhalter who adds: "although one of the reasons I download taxonomies, and supplement said data with PBDB and other resources not indexed by PBDB (major higher level revisions with no new occurrences), and add ichnotaxa not in IRMING, is so I have a local copy on my CMS."

**Comment by dimus** [comment]
Closing as stale
