### ISSUE TITLE
More names with problematic epithets

### ISSUE THREAD

**Issue by KatjaSchulz** [gnames/gnparser#191]
These are all accepted species names from COL2021-07-29.  I don't think any of them are database artifacts.

Here's another one for the "nudum" whitelist:

Microsiphum nudum

Names with short epithets that are interpreted as part of the author data:

Selenops ab Logunov & Jäger, 2015
Ruteloryctes bis Dechambre, 2006
Antaplaga dela Druce, 1904
Baeolidia dela (Er. Marcus & Ev. Marcus, 1960)
Dicentria dela Druce, 1894
Epeloria dela Chamberlin, 1946
Eulaira dela Chamberlin & Ivie, 1933
Paralvinella dela Detinova, 1988
Scoparia dela Clarke, 1965
Tortolena dela Chamberlin & Ivie, 1941
Semiothisa da Dyar, 1916
Gnathopleustes den (J.L. Barnard, 1969)
Agnetina den Cao, T.K.T. & Bae, 2006
Desmoxytes des Srisonchai, Enghoff & Panha, 2016
Meteorus dos Zitani, 1998
Stenoecia dos Freyer, 1838
Sympycnus du Curran, 1929
Bolitoglossa la Campbell, Smith, Streicher, Acevedo & Brodie, 2010
Leptonetela la Wang & Li, 2017
Nocaracris van Ünal, 2016
Zodarion van Bosmans, 2009
Malamatidia zu Jäger & Dankittipakul, 2010

Names with ser/subser epithets that are interpreted as rank information or end up in an unparsed tail:

Helophorus (Lihelophorus) ser Zaitzev, 1908
Serina ser Gredler, 1898
Serina subser Gredler, 1898

Names with strange epithets that end up in an unparsed tail:

Seleuca chûjôi Voss, 1957
Peperomia non-alata Trel.
Hyacinthoides non-scripta (L.) Chouard ex Rothm.
Monocelis non-scripta Curini-Galletti, 2014
Macromitrium st.-johnii E. B. Bartram, 1940

Names with seemingly innocuous epithets that nevertheless end up in an unparsed tail:

Profusulinella оblопgа Potievskaya, 1964
Tetrataxis toгosus Postoyalko, 1975
Anomalina badkhyseпsis Kuryleva, 1973
Bigenerina iпfrapaleogenica Suleymanov, 1963
Carpelimus (Trogophloeus) rougemoпti Gildenkov, 2014

**Comment by dimus** [comment]
```
Names with seemingly innocuous epithets that nevertheless end up in an unparsed tail:

Profusulinella оblопgа Potievskaya, 1964
Tetrataxis toгosus Postoyalko, 1975
Anomalina badkhyseпsis Kuryleva, 1973
Bigenerina iпfrapaleogenica Suleymanov, 1963
Carpelimus (Trogophloeus) rougemoпti Gildenkov, 2014
```
All of these contain characters that not suppose to be in scientific names: `п`, `г`, so they are not parsed correctly

**Comment by dimus** [comment]
```
Selenops ab Logunov & Jäger, 2015
Ruteloryctes bis Dechambre, 2006
Antaplaga dela Druce, 1904
Baeolidia dela (Er. Marcus & Ev. Marcus, 1960)
Dicentria dela Druce, 1894
Epeloria dela Chamberlin, 1946
Eulaira dela Chamberlin & Ivie, 1933
Paralvinella dela Detinova, 1988
Scoparia dela Clarke, 1965
Tortolena dela Chamberlin & Ivie, 1941
Semiothisa da Dyar, 1916
Gnathopleustes den (J.L. Barnard, 1969)
Agnetina den Cao, T.K.T. & Bae, 2006
Desmoxytes des Srisonchai, Enghoff & Panha, 2016
Meteorus dos Zitani, 1998
Stenoecia dos Freyer, 1838
Sympycnus du Curran, 1929
Bolitoglossa la Campbell, Smith, Streicher, Acevedo & Brodie, 2010
Leptonetela la Wang & Li, 2017
Nocaracris van Ünal, 2016
Zodarion van Bosmans, 2009
Malamatidia zu Jäger & Dankittipakul, 2010
```
these are tricky, I have to think what to do

**Comment by dimus** [comment]
ambiguous names should be parsed now without conswquences for other names (hopefully). The solution is a bit hackish, but should work

**Comment by abubelinha** [comment]
Is _chûjôi_ a valid epithet? I don't think accents are accepted in latin or latinized names at all.

> Seleuca chûjôi Voss, 1957

**Comment by abubelinha** [comment]
> All of these contain cyrillic characters that not supposed to be in scientific names: `п`, `г`, so they are not parsed correctly
> 
> I bet whoever entered them was in the middle of replying to their instant message :D

Those cyrillic characters do so much resemble n and r Latin characters. Very difficult to detect them when looking at an excel file. Would it be possible for gnparser to automatically detect and replace them for their Latin equivalents, and rise a quality warning?
