### ISSUE TITLE
old 32bit Windows binary request

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnparser#192]
Our database runs on an old 32bit Windows XP machine.

Are there any chances to find a gnparser binary which we can use there? (even if it is an old version)
Thanks a lot in advance

**Comment by dimus** [comment]
@abubelinha I made an experimentatl win32 binary for v1.3.3, can you check if it works?

**Comment by abubelinha** [comment]
Thanks @dimus I suppose this is the file:
https://github.com/gnames/gnparser/releases/download/v1.3.3/gnparser-v1.3.3-win-32.zip

I uncompressed it and tried the executable in that machine, but I got a messagebox saying "gnparser.exe is not a valid Win32 application"

On my Win7 64bit laptop, it worked perfectly (like the 64bit gnparser version).

**Comment by abubelinha** [comment]
BTW the machine has Microsoft Windows XP Professional v.2002, with Service Pack 3
Intel(R) Core(TM)2 Quad CPU, Q9450 @ 2.66GHz
RAM 3.48 GB

**Comment by dimus** [comment]
I removed the binary for win32, I guess there is no easy solution for this. Is it possible for you to access REST api at https://parser.globalnames.org? It is very fast, especially if you send names in butches of several thousands.

**Comment by abubelinha** [comment]
OK. I’ll try that.
I guess I should follow the POST example here? https://github.com/gnames/gnparser/blob/master/README.md#usage-as-a-rest-api-interface

**Comment by dimus** [comment]
yes, you can also use https://apidoc.globalnames.org/gnparser to play with API,  get a feel of it, and also it describes all JSON fields of the output.

**Comment by dimus** [comment]
Closing this ticket. Looks like there is no easy solution, and the number of win32 users is small and is decreasing, so we are skipping this binary. Looks like remote use of https://parser.globalnames.org API  is a solution here.

**Comment by abubelinha** [comment]
Just for reference, this is what I finally did:

1) Install gnparser on another machine of the LAN (i.e., IP 192.168.1.100)
2) Start a gnparser server in that machine with `gnparser -p 8080`
3) Make calls to that server from Win32 machines. A minimal Python example:

```Python
 	url = "http://192.168.1.100:8080/api/v1/"
	data = {
	  "names": [
		"Pleurosigma vitrea var. kjellmanii H.Peragallo, 1891a",
		"Bubo bubo"
	  ],
	  "withDetails": True,
	  "csv": False
	}
	import requests
	response = requests.post(url, json=data)
	print(response)
```

Thanks!

**Comment by dimus** [comment]
@abubelinha, it is a reasonable approach. What is the project you use gnparser for? Just curious

**Comment by abubelinha** [comment]
Nothing really very specific. This is not for a particular project.

I am just tired of having to develop my own quick & dirty functions for comparing "canonical names" coming from different sources (online checklists, gbif data, my own field notes, and different collection databases in a variety of file formats ... some of them maintained in old Win32 machines).
A gnparser server is easy to implement, and  I find python scripts are pretty compatible with all machines I use (I hope).

**Comment by abubelinha** [comment]
I am not sure this deserves a new issue or not.
I was wondering how many names is it advisable to include in a single server api call.

If y have 45000 names to parse, is it better (for the server) to receive 45 calls, 1000 names each call ... or just one call with 45000 names?

On the other hand I guess my Win32 Python application will probably prefer not to parse such a big json response all at once. 
But that's another question. Right now I am asking about remote server health.

**Comment by dimus** [comment]
I would say 50000 names should be OK for one call

**Comment by dimus** [comment]
> On the other hand I guess my Win32 Python application will probably prefer not to parse such a big json response all at once.

Also note that gnparser does not generate one json with 50000 elements, it generates 50000 json strings. So for python it does not really matter, I think, to parse 1 name or 50000, except of the memory spent to keep al 50000 json strings
