### ISSUE TITLE
More "nudum" names which don't parse correctly

### ISSUE THREAD

**Issue by tobymarsden** [gnames/gnparser#207]
[Here is a list](https://github.com/gnames/gnparser/files/7535204/nudum.txt) of 119 names from World Flora Online and Plants of the World Online containing the epithet "nudum" which don't parse correctly. I'm happy to submit a PR which adds them to the existing list of "nudum" exceptions, if that is the best approach?

**Comment by dimus** [comment]
Thanks @tobymarsden, great list. I see that some of the names are infraspecific, that means the solution I have need to be extended for them, before all names were species. PR would be fantastic, or I can get to it at some point this week.

**Comment by tobymarsden** [comment]
@dimus Sure thing; I'll work on a PR in the coming days.

I'm also seeing a bunch more names with `non-` epithets not parsing correctly; is there scope for changing the regex to only match `non` where it's not followed by a dash? Or is that likely to catch detritus that should be moved to the tail?
