### ISSUE TITLE
Epithets starting with `non` are not parsed correctly

### ISSUE THREAD

**Issue by tobymarsden** [gnames/gnparser#211]
Currently names such as `Hyacinthoides non-scripta` have to be special-cased because `non` is a stopword.

There are also a bunch of these names which are not currently handled:

```
Artocarpus altilis var. non-seminiferus
Artocarpus incisus var. non-seminiferus
Asarum maculatum var. non-maculatum
Asarum versicolor var. non-versicolor
Hyacinthus non-scriptus
Hylomenes non-scripta
Grossularia non-scripta
Scilla non-scripta subsp. hispanica
Usteria non-scripta
Anthericum non-ramosum
Anthericum non-scriptum
Endymion non-scriptus
Streptanthera cuprea var. non-picta
Scilla non-scripta subsp. cernua
Torreya grandis f. non-apiculata
Rosa ×pouzinii subsp. nonhispida
Cotoneaster non-shan
Ribes non-scriptum
```

The most conservative way of handling this would be to change the `non` stopword into `non\s` -- this would retain the current behavior in the case of inputs such as `Xiphipops fisheri (non Snyder, 1904)` but allow epithets starting with `non-` to be parsed.

**Comment by abubelinha** [comment]
Hold on. There is something odd here.

_Hyacinthoides non-scripta_ [was reported as one of these cases](https://github.com/gnames/gnparser/issues/199), but current version of the online parser (v1.5.5) is already resolving it correctly ([quality 1](https://parser.globalnames.org/?format=html&names=Hyacinthoides+non-scripta&with_details=on))

But the others @tobymarsden mentions now are getting quality 4 (unparsed tails)
What's the explanation for this [different behaviour](https://parser.globalnames.org/?format=html&names=Hyacinthoides+non-scripta%0D%0A----------------------------------%0D%0AArtocarpus+altilis+var.+non-seminiferus%0D%0AArtocarpus+incisus+var.+non-seminiferus%0D%0AAsarum+maculatum+var.+non-maculatum%0D%0AAsarum+versicolor+var.+non-versicolor%0D%0AHyacinthus+non-scriptus%0D%0AHylomenes+non-scripta%0D%0AGrossularia+non-scripta%0D%0AScilla+non-scripta+subsp.+hispanica%0D%0AUsteria+non-scripta%0D%0AAnthericum+non-ramosum%0D%0AAnthericum+non-scriptum%0D%0AEndymion+non-scriptus%0D%0AStreptanthera+cuprea+var.+non-picta%0D%0AScilla+non-scripta+subsp.+cernua%0D%0ATorreya+grandis+f.+non-apiculata%0D%0ARosa+%C3%97pouzinii+subsp.+nonhispida%0D%0ACotoneaster+non-shan%0D%0ARibes+non-scriptum) of gnparser with similar epithets?

**Comment by dimus** [comment]
for these specific names I quess we need a look-ahead with '-'
non\b can be the last word in a name string, word with space, word with some other non-letter.

There is a broader situation where names like "Aus bus (non Linnaeus)"  would benefit from properly parsed "non", but it can be addressed in a separate issue.

**Comment by tobymarsden** [comment]
@dimus considering the absence of lookarounds in golang's regex, this is ugly but appears to work:

```
var notesRe = regexp.MustCompile(
	`(?i)\s+((environmental|samples|species\s+group|species\s+complex|clade|group|author|nec|vide|fide)\b|non[^a-zA-Z-]).*$`,	
)
```

Have I missed anything?

(`non` is already in the `lastWordJunkRe` regex so ignoring that here).

**Comment by dimus** [comment]
yes, lets try it this way, looks like lookahead is not included for performance reasons
