### ISSUE TITLE
Missing year in quality-2 parse

### ISSUE THREAD

**Issue by jar398** [gnames/gnparser#212]
Similar examples have a value in the `Year` column; don't know why this one doesn't.
```
gnparser "Ozimops kitcheneri Reardon, McKenzie, & Adams in Reardon, McKenzie, S. J. B. Cooper, Appleton, Carthew, & Adams, 2014"
Id,Verbatim,Cardinality,CanonicalStem,CanonicalSimple,CanonicalFull,Authorship,Year,Quality
2ab21aa7-aa39-56e4-ba40-b1b8cd2ac0ae,"Ozimops kitcheneri Reardon, McKenzie, & Adams in Reardon, McKenzie, S. J. B. Cooper, Appleton, Carthew, & Adams, 2014",2,Ozimops kitchener,Ozimops kitcheneri,Ozimops kitcheneri,"Reardon, Mc Kenzie & Adams ex Reardon, Mc Kenzie, S. J. B. Cooper, Appleton, Carthew & Adams 2014",,2
```

**Comment by dimus** [comment]
@jar398 good catch, I think in such situation as in your example: `Aus bus A. in B. 1888` the year from `ex` authors should be presented as a year of a name.

**Comment by jar398** [comment]
Yeah I would think so too - in this case another string for the same taxonomic name is without the 'ex' and the authors and year are those for the 'ex'... I would think the reason for doing 'ex' is to provide the publication that makes the name available, in which case the year would be the year of publication, as usual? But then I'm not a taxonomist.

**Comment by jar398** [comment]
I'm also a bit concerned about the spaces after `Mc` but can report that as a separate issue

**Comment by dimus** [comment]
Neither am I a taxonomists, but what taxonomists told me, `ex` and `in` for botanical names (`Aus bus A. ex B.`) means that author `A.` described species but  cic not jump through all hooks, and later `B.` described species properly based on the original description by A.

For example `B.` found a herbarium sheet with new species collected by `A.` with a description attached, then used the description in a publication.

In ICZN as I undertstand it is opposite, and `A.` would properly publish unfinished description by `B.`. Also, as I understand by ICZN `ex B.` mention of original author is concidered unnecessary, so the name in question strictly speaking should probably be:
`Ozimops kitcheneri Reardon, McKenzie, & Adams, 2014`

However, as I understand, people do not always follow the rules and in zoological names sometimes do add `ex` authors, or even use botanical `ex` format.

**Comment by dimus** [comment]
https://en.wikipedia.org/wiki/Author_citation_(botany)#Usage_of_the_term_%22ex%22


```
    Andropogon aromaticus Sieber ex Schult.

indicates that Josef Schultes validly published this name (in 1824 in this instance), but his description was based on an earlier description by Franz Sieber. (Note that in botany, the author of the earlier name precedes the later, valid one; in zoology, this sequence (where present) is reversed.) 
```

Also

https://en.wikipedia.org/wiki/Author_citation_(zoology)
