### ISSUE TITLE
Problems name strings with author names containing "degli"

### ISSUE THREAD

**Issue by KatjaSchulz** [gnames/gnparser#224]
Such author names are usually constructed with two family names separated by "degli" 
gnparser interprets the degli as an epithet.  

Examples: 

Sylvia atricapilla pauluccii Arrigoni degli Oddi, 1902
Cestodiscus gemmifer F. S. Castracane degli Antelminelli

**Comment by dimus** [comment]
Thanks @KatjaSchulz! Hm interesting, I was not aware about `degli`

**Comment by KatjaSchulz** [comment]
I think it's pretty rare. I could find only a couple of authors with a dozen species between them. For what it's worth, I couldn't find a single species with a legitimate "degli" epithet, so I think it's probably safe to always interpret it as part of an Italian author name.
