### ISSUE TITLE
Use "mihi" to enhance scientific name finding and parsing

### ISSUE THREAD

**Issue by Archilegt** [gnames/gnparser#230]
The Latin word "mihi" was used by authors when proposing new scientific names, with the meaning of "me". The word could be used as a marker for "scientific name ends here", and could enhance scientific name finding if coupled to "search for scientific name 1, 2, 3 words ahead". 
The word could also be used for adding "interpreted authorship" (author+date) to scientific names instances if coupled to the publication (book, article) metadata where the scientific name instance is matched, therefore potentially helping to disambiguate homonyms.
A quick glance at the occurrence of the word in BHL: https://www.biodiversitylibrary.org/search?searchTerm=mihi&stype=F#/titles
Maybe it would be worth trying at least the "scientific name ends here" suggestion? :)

**Comment by Archilegt** [comment]
Many thanks, Dima!
Good to know that if "mihi" is applied, it may give "false positives" in a very small subset of names, compared to the "true positives" for which it does represent a terminal element.

**Name deduplication:** I believe that for the sake of counting potentially affected names, the 20 name instances that you found can be deduplicated down to 15, as follows:
- Minus two instances of three Anisochaeta kiwi mihi
- Minus one instance of two Conferva geminata var. mihi
- Minus one instance of two Eucyclops serrulatus mihi
- Minus one instance of Lithobius leostygis mihi and Lithobius (Polybothrus) leostygis subsp. mihi because the gnparser will cut the subgeneric name off.

Deduplicated list of names: 
1. Aeolesthes inhirsutus mihi
2. Anisochaeta kiwi mihi Blakemore 2012
3. Bruchus nongoniermani Mihi,
4. Chimila tinguana mihi
5. Chyphononyx simulator mihi
6. Cobosidea mihi
7. Conferva geminata var. mihi Schwabe
8. Eucyclops serrulatus mihi Dussart, Graf & Husson, 1966
9. Hypomyces chrysospermus f. edulis-mihi K. Bitner 1953
10. Lithobius leostygis mihi and Lithobius (Polybothrus) leostygis subsp. mihi
11. Lithobius (Polyrbothrus) caesar subsp. mihi
12. Odonthophagus var. c mihi
13. Quexua alinella mihi
14. Scutella agassizi mihi
15. Trochus patholatus mihi

**Comment by Archilegt** [comment]
**Names by Plazi:**
  
Scientific name: Lithobius (Poly**r**bothrus) caesar mihi
https://tb.plazi.org/GgServer/html/299583C14F747A72E86065049FDE3C22
A misspelling for Polybothrus, plus a digitization artifact which should not have included "mihi".
Published string is spelled and styled correctly, as "4. _Lithobius (Polybothrus) caesar_ mihi."
See https://www.biodiversitylibrary.org/page/13294205

Scientific name: Lithobius (Polybothrus) leostygis subsp. mihi
https://tb.plazi.org/GgServer/html/CCEB9C62C87766E980DD858BC13468C8
A digitization artifact which should not have included "mihi".
Published string is styled correctly, as "1. _Lithobius (Polyhothrus) leostygis_ mihi".
See See https://www.biodiversitylibrary.org/page/13294201

Scientific name: Lithobius leostygis mihi
This instance points to the one above and I could not find a URL for it.

**Result:** The three (two when deduplicated) scientific name instances contributed by Plazi are false-positive digitization artifacts, including a misspelling.

Deduplicated list of names v.2 (Plazi names cleared):

    Aeolesthes inhirsutus mihi
    Anisochaeta kiwi mihi Blakemore 2012
    Bruchus nongoniermani Mihi,
    Chimila tinguana mihi
    Chyphononyx simulator mihi
    Cobosidea mihi
    Conferva geminata var. mihi Schwabe
    Eucyclops serrulatus mihi Dussart, Graf & Husson, 1966
    Hypomyces chrysospermus f. edulis-mihi K. Bitner 1953
    Odonthophagus var. c mihi
    Quexua alinella mihi
    Scutella agassizi mihi
    Trochus patholatus mihi

**Comment by Archilegt** [comment]
**Anomaly:** The name "Odonthophagus var. c mihi", coming from ION has so many anomalies that it seems irrelevant to GNA for name finding.
Source anomalies: The generic name is given as both "Onthophagus" (https://www.biodiversitylibrary.org/page/8222096) and "Odonthophagus" (https://www.biodiversitylibrary.org/page/8221999) in the "Enumeratio Insectorum Norvegicorum. Fasciculus ii." which ION points to. Additionally, it is not a scientific name in itself, e.g., it is the name of a variety designated by a single letter.
Digitization anomalies: Name digitized with the genus "Odonthophagus" instead of ""Onthophagus". Name not including the specific epithet, supposedly "fracticornis", to which "var. c" is to be ascribed. The "mihi" seems to be a false positive, added by the recorder, as it is not a text string in the referred publication.

Overall, the name can be considered a false positive for mihi and can be deleted from the list.

Deduplicated list of names v.2 (Plazi names cleared):
1. Aeolesthes inhirsutus mihi
2. Anisochaeta kiwi mihi Blakemore 2012 (**true positive**, a regrettable alternative to mihiensis)
3. Bruchus nongoniermani Mihi,
4. Chimila tinguana mihi
5. Chyphononyx simulator mihi
6. Cobosidea mihi
7. Conferva geminata var. mihi Schwabe (**AlgaeBase, taxon?**)
8. Eucyclops serrulatus mihi Dussart, Graf & Husson, 1966
9. Hypomyces chrysospermus f. edulis-mihi K. Bitner 1953 (**Union 4, Fungi: Ascomycota**)
10. Quexua alinella mihi
11. Scutella agassizi mihi
12. Trochus patholatus mihi

@dimus, could someone check the "algal" and fungal names for you, so that we can know if they are true or false positives? A copy of the original publication would be desirable.

**Comment by dimus** [comment]
Word `mihi` happens 192254 times in BHL

**Comment by Archilegt** [comment]
"Conferva geminata var. mihi Schwabe" may be hard to match. The combination is uncurated in AlgaeBase and there is no guarantee that it is an original combination. There are no recorded references for that combination.
The original combination may be _Oscillatoria geminata_ Schwabe. When searched for that combination and author, AlgaeBase returns "_Oscillatoria geminata_ Schwabe ex Gomont 1892" (https://www.algaebase.org/search/species/detail/?species_id=51094), which is also not the original treatment.
The original treatment for _Oscillatoria geminata_ Schwabe can be found at:
Linnaea 11 (1), year 1837
Page 118: https://www.biodiversitylibrary.org/page/35312749
Tab. 1, Fig. 7: https://www.biodiversitylibrary.org/page/35313360

Confirming whether these are two combinations of the same name and whether the "mihi" is an artifact would require consulting with specialists familiar with the historical literature on _Conferva_ and _Oscillatoria_. However, that is likely the case, as the author matches and there are currently combinations under both genera for a few species.

**Comment by Archilegt** [comment]
Aeolesthes inhirsutus mihi seems another false positive.
The name string "_Aeolesthes inhirsutus_ subsp. _mihi_ M.Matsushita, 1932" is deleted from GBIF (https://www.gbif.org/species/8885942).
The string may have reached GBIF via JBIF (Japan). See entry for holotype of "Aeolesthes inhirsutus subsp. mihi M.Matsushita, 1932" at https://www.gbif.jp/gbif_search/detail?id=1_sehu-cole_urn:catalog:SEHU:COLE:0000000191

**Comment by dimus** [comment]
Hmm, looks like situation is even more interesting with `mihi`:

https://www.biodiversitylibrary.org/item/181042#page/535/mode/1up

``Characium obovatum mihi. b. var. longipes mihi``

I wonder if a better approach to `mihi` is to ignore it, instead of considering it the end of a name.

**Comment by dimus** [comment]
Thank you @Archilegt for interesting information about`Eucyclops serrulatus mihi`, I'll pass it along to CoL guys. Do I understand correctly, that in zoology old names with `var.` or `f.` sometimes are promoted to subspecies rank? I would still add `Eucyclops serrulatus mihi` as an exception, because parser is not a nomenclatural authority and deals with data on a lexical level.

**Comment by Archilegt** [comment]
Hi @dimus 
I reported the issue with E. s. mihi to T. Chad Walter (https://www.marinespecies.org/copepoda/index.php) on 13.vi.2022 but I did not receive a reply. Maybe the COL will be able to reach him or someone else. Thanks!

**Comment by Archilegt** [comment]
Hi @dimus 
The case of `Characium obovatum mihi. b. var. longipes mihi` (https://www.biodiversitylibrary.org/page/47100016) is interesting. There you don't have one name but two. The string would be parsed by a human reader as:
Tab. VII. 
Fig. 3. `Characium obovatum mihi`
Fig. 3`b`. `Characium obovatum var. longipes mihi`
where "b" is not part of the name but the explanation of an illustration (https://www.biodiversitylibrary.org/page/47100082).
The two mihi are indeed to be parsed as terminators but the first one could be also recognized as a connector. Detecting and reconstructing two names and recognizing a "b" as a figure indication might be too much to ask from a parser and could be left to a layer of annotations.
For strings less complex (e.g., without the "b") and containing two `mihi`, where `Genus specificEpithet mihi [var., f.] subspecificEpithet mihi` the parsing would be:
```
if 2 mihi, 
parse mihi 1, 
connect specificEpithet to subspecificEpithet, 
terminate before mihi 2
```

"...in zoology old names with var. or f. sometimes are promoted to subspecies rank?"
Yes, you are correct. The ZooCode has article "45. The species group", where article "45.5. Infrasubspecific names." The references therein will guide you to other articles.

**Comment by Archilegt** [comment]
Hi @dimus 
Shall we keep this issue open for some preliminary reporting on improved parsing? Or shall we do that via email or GoogleDocs? It would be great to have some stats on the actual improvement of the parser! :D

**Comment by dimus** [comment]
I do not have yet `b. var.` as a possible rank (not yet sure how common it is, to justify adding it to parsing). The parsing of `Characium obovatum mihi. var. longipes mihi` is now `Characium obovatum var. longipes`:

https://github.com/gnames/gnparser/blob/master/testdata/test_data.md#names-with-mihi

I think it is reasonable enough to close the ticket for now, especially because the parser does not deal with names that happen in biological texts, and it is extremely rare to have `mihi` in prepared lists of names.

**Comment by Archilegt** [comment]
Dima, please note that `b. var.` is not a rank.
`b` refers to figure 3b
`var.` is a rank

**Comment by dimus** [comment]
Ah thank you for spotting it @Archilegt!

> Dima, please note that `b. var.` is not a rank. `b` refers to figure 3b `var.` is a rank

Making gnfinder ticket about it https://github.com/gnames/gnfinder/issues/125

**Comment by dimus** [comment]
@Archilegt, do you think it makes better sense for to parse `Characium obovatum mihi. var. longipes mihi` as `Characium obovatum` with `var. longipes mihi` ans an unparseable tail? The parser does assume that a string must have only one name.

**Comment by Archilegt** [comment]
"do you think it makes better sense to parse Characium obovatum mihi. var. longipes mihi as Characium obovatum with var. longipes mihi as an unparseable tail? The parser does assume that a string must have only one name."
No, I think that when choosing among two name strings, one should aim at retrieving the longest and most informative string along with the shortest unparseable tail. As it is now.

"I tend to think about this string as an indication of implicit authorship in two places, kind of similar to Aus bus L. cus K."
Yes, that would be the case for `Characium obovatum mihi. var. longipes mihi`.
However, here we have **Fig 3.** `Characium obovatum mihi`**. b.** `var. longipes mihi`
In an ideal world, the parser would:
1. Execute a first parsing, with `Fig.` #langEn or `Abb.` #langDE followed by Arabic or Roman numerals ranking higher than `scientificName`. If `Fig.` or `Abb.` and numerals are detected, parse accordingly and wrap the whole string or substrings as `explanationOfFigure`
2. Execute a second parsing for `#ordered letters` where `#a can be ommitted` and scoring letters higher if they are `#letters enclosed by periods`. Wrap resulting `explanationOfSubfigure`.
3. Trigger name detection within each `explanationOfSubfigure`, with allowed values for single words `specificEpithet` and `subspecificEpithet`. Increase posterior score for `explanationOfSubfigure` wrappers if `mihi` terminators or `authorName` co-occur with periods of `#ordered letters`.
4. Trigger name reconnection for `explanationOfSubfigure` values b to z if single word values `specificEpithet` and `subspecificEpithet` exist. Match `subspecificEpithet` to nearest anterior `specificEpithet`, match both to nearest anterior `genus` in order to assemble `scientificName`.

Example for **Fig 3.** `Characium obovatum mihi`**. b.** `var. longipes mihi`:
1. `<explanationOfFigure>Fig 3. Characium obovatum mihi. b. var. longipes mihi</explanationOfFigure>`  #langEn #numeralArabic

2. `<explanationOfFigure>Fig 3. 
           <explanationOfsubfigure>Characium obovatum mihi.</explanationOfsubfigure> #aOmmitted #wrapperScore = 0.25
           <explanationOfsubfigure>b. var. longipes mihi</explanationOfsubfigure> #bFirstLetter #wrapperScore = 0.25
    </explanationOfFigure>`

3. `<explanationOfFigure>Fig 3. 
           <explanationOfsubfigure>Characium obovatum mihi.</explanationOfsubfigure> #mihi #wrapperPostScore = 0.50
           <explanationOfsubfigure>b. var. longipes mihi</explanationOfsubfigure> #mihi #wrapperPostScore = 0.50 `subspecificEpithet` = true
    </explanationOfFigure>`

4. `<explanationOfFigure>Fig 3. 
           <explanationOfsubfigure>Characium obovatum mihi.</explanationOfsubfigure> #scientificName = Characium obovatum
           <explanationOfsubfigure>b. var. longipes mihi</explanationOfsubfigure> #bFirstLetter #scientificNameAssembled = Characium obovatum var. longipes
    </explanationOfFigure>`

Does it make sense?

**Comment by dimus** [comment]
I think what you say is more of a job for `gnfinder`, because `gnparser` is designed to work with lists of already processed scientific names like personal checklists, databases, already extracted names. Adding contraints on what gnparser can do allows to decrease number of false positives. 

Lets say  `Characium obovatum mihi. b. var. longipes mihi` is in a database. Parser would return:

http://parser.globalnames.org/?format=html&names=Characium+obovatum+mihi.+b.+var.+longipes+mihi&with_details=on

with lowest parsing quality 4 and 2 warnings: unparsed tail and ignored annotation, which would allow database or checklist curator to detect a problem, look at it and fix it by hand

```
{
  "parsed": true,
  "quality": 4,
  "qualityWarnings": [
    {
      "quality": 4,
      "warning": "Unparsed tail"
    },
    {
      "quality": 3,
      "warning": "Ignored annotation `mihi`"
    }
  ],
  "verbatim": "Characium obovatum mihi. b. var. longipes mihi",
  "normalized": "Characium obovatum",
  "canonical": {
    "stemmed": "Characium obouat",
    "simple": "Characium obovatum",
    "full": "Characium obovatum"
  },
  "cardinality": 2,
  "tail": " b. var. longipes mihi",
  "details": {
    "species": {
      "genus": "Characium",
      "species": "obovatum"
    }
  },
  "words": [
    {
      "verbatim": "Characium",
      "normalized": "Characium",
      "wordType": "GENUS",
      "start": 0,
      "end": 9
    },
    {
      "verbatim": "obovatum",
      "normalized": "obovatum",
      "wordType": "SPECIES",
      "start": 10,
      "end": 18
    }
  ],
  "id": "e65f7279-c3f1-5719-9058-a3c024719fde",
  "parserVersion": "v1.6.7"
}
```
