### ISSUE TITLE
A few more names that don't parse due to strange epithets

### ISSUE THREAD

**Issue by KatjaSchulz** [gnames/gnparser#231]
Turkozelotes attavirus Chatzaki, 2019 - https://wsc.nmbe.ch/species/57618
Phalium (Semicassis) vector R. T. Abbott, 1993 - https://www.marinespecies.org/aphia.php?p=taxdetails&id=1512712
Spirophora bacterium Lendenfeld, 1887 - https://www.marinespecies.org/aphia.php?p=taxdetails&id=193539

**Comment by dimus** [comment]
Thank you @KatjaSchulz! I am back from vacation, will look it it today
