### ISSUE TITLE
Names of subgenera don't get parsed if subgen. is included in the scientific name value

### ISSUE THREAD

**Issue by KatjaSchulz** [gnames/gnparser#232]
Psammophanes subgen. Psammophrynopsis Koch, 1953 parses fine, with a warning.

subgen. Psammophrynopsis Koch, 1953 doesn't get parsed at all.

It would be good if names preceded by subgen. would get parsed. They do occur in the wild, e.g. in current Catalogue of Life files.

**Comment by dimus** [comment]
hm, interesting, @gdower, do you know how often such names happen?

**Comment by gdower** [comment]
It's not super-common in the datasets that I work with, but I do see it occasionally. In World Plants/World Ferns, 0.83% of the lines include "subgen." Often in that source it's included like this: subgen. Filago (without the genus included).

**Comment by KatjaSchulz** [comment]
Sorry, I should have provided more context. There are 38 subgenera with this scientificName structure in the current version of COL (2022-07-12). 

[colSubgen.txt](https://github.com/gnames/gnparser/files/9376907/colSubgen.txt)

These are derived from two different sources, both entomological:
[World catalogue of the tribe Sepidiini (Tenebrionidae, Coleoptera)](https://www.catalogueoflife.org/data/dataset/1206) and [Lygaeoidea Species File](http://www.catalogueoflife.org/data/dataset/1173)

**Comment by KatjaSchulz** [comment]
I'm not really in a position to evaluate whether it would be worth it. For the time being, we can handle these through post-processing. We can revisit if we encounter more cases with this usage.

**Comment by gdower** [comment]
@yroskov and I are aiming to fix those names in the Sept release of CoL.

**Comment by dimus** [comment]
@gdower @yroskov, is it fixed in CoL, can this issue be closed?

**Comment by dimus** [comment]
Parsing it now like this:

```json
{
  "parsed": true,
  "quality": 2,
  "qualityWarnings": [
    {
      "quality": 2,
      "warning": "Uninomial prepended by its rank"
    }
  ],
  "verbatim": "subgen. Psammophrynopsis Koch, 1953",
  "normalized": "subgen. Psammophrynopsis Koch 1953",
  "canonical": {
    "stemmed": "Psammophrynopsis",
    "simple": "Psammophrynopsis",
    "full": "subgen. Psammophrynopsis"
  },
  "cardinality": 1,
  "rank": "subgen.",
  "authorship": {
    "verbatim": "Koch, 1953",
    "normalized": "Koch 1953",
    "year": "1953",
    "authors": [
      "Koch"
    ],
    "originalAuth": {
      "authors": [
        "Koch"
      ],
      "year": {
        "year": "1953"
      }
    }
  },
  "details": {
    "uninomial": {
      "uninomial": "Psammophrynopsis",
      "rank": "subgen.",
      "authorship": {
        "verbatim": "Koch, 1953",
        "normalized": "Koch 1953",
        "year": "1953",
        "authors": [
          "Koch"
        ],
        "originalAuth": {
          "authors": [
            "Koch"
          ],
          "year": {
            "year": "1953"
          }
        }
      }
    }
  },
  "words": [
    {
      "verbatim": "subgen.",
      "normalized": "subgen.",
      "wordType": "RANK",
      "start": 0,
      "end": 7
    },
    {
      "verbatim": "Psammophrynopsis",
      "normalized": "Psammophrynopsis",
      "wordType": "UNINOMIAL",
      "start": 8,
      "end": 24
    },
    {
      "verbatim": "Koch",
      "normalized": "Koch",
      "wordType": "AUTHOR_WORD",
      "start": 25,
      "end": 29
    },
    {
      "verbatim": "1953",
      "normalized": "1953",
      "wordType": "YEAR",
      "start": 31,
      "end": 35
    }
  ],
  "id": "1b8f7c8c-16c8-5411-a992-f7945f0e3838",
  "parserVersion": "v1.9.2-5-g93e2782"
}
```

**Comment by dimus** [comment]
part of v1.10.0 release now
