### ISSUE TITLE
Installation (tutorial suggestion regarding env path)

### ISSUE THREAD

**Issue by ggrittz** [gnames/gnparser#233]
Hi,

I was following the tutorial for Windows installation and the "[Add C:\bin directory to your PATH](https://www.computerhope.com/issues/ch000549.htm) environment variable." link recommends adding the env variable to **system variables**. However, I had to add to **users variables** to properly work. Windows is batshit sorcery. Maybe suggest both?

Cheers.

**Comment by dimus** [comment]
Thanks @ggrittz for spotting this! Does this sound better?

https://github.com/gnames/gnparser/commit/6ab984e23d171050a7855f436adfd9a833f1f743

I am scared of Windows' sorcery :)
