### ISSUE TITLE
Stemming -ii

### ISSUE THREAD

**Issue by jar398** [gnames/gnparser#238]
Maybe this intentional but I ran into this problem and thought I'd ask... I see the following two stemming results:

    Notopteris macdonaldi   -> macdonald
    Notopteris macdonaldii  -> macdonaldi

I would naively expect the entire -ii suffix to be removed when stemming, so that these two epithets can be seen as equivalent.

Another: Sorex bairdi  / bairdii .  Examples are from MSW3 vs. MDD.

I am running v1.5.2; apologies if this has been fixed already.

Thanks

**Comment by dimus** [comment]
we used an example list from https://snowballstem.org/otherapps/schinke/ where names like 'aduersarii` stemmed to 'aduersari'. I am not sure it is right, we probably need to find an alternative algorithm, or make one based on a Latin linguist advise.

**Comment by jar398** [comment]
Thanks!
