### ISSUE TITLE
Why `’` is converted to `'`?

### ISSUE THREAD

**Issue by dimus** [gnames/gnparser#247]
From https://github.com/gnames/gnparser/issues/245 

Another issue is that "D'Orbigny" in the original is "D’Orbigny" in the gnparser output. Why change UTF-8 27 to e2 80 99?

**Comment by Mesibov** [comment]
@dimus, I've rechecked the original dataset and found that the compilers used both characters:
3 records	Acteocina candei (D’Orbigny, 1841)
37 records	Acteocina candei (D'Orbigny, 1842)

gnparser converted both to apostrophe in Author, which is OK. I was looking at "D’Orbigny" in the verbatim field and thinking I had inputted "D'Orbigny", so my mistake, all is well. In my pseudo-duplicate [search](https://discourse.gbif.org/t/using-gnparser-to-check-scientificname-entries/4145) the results are fine:

Acteocina candei (D'Orbigny, 1841)  [3]
Acteocina candei (D'Orbigny, 1842)  [37]
