### ISSUE TITLE
Documentation in README incorrect

### ISSUE THREAD

**Issue by joelnitta** [gnames/gnparser#250]
The README says:

> --cultivars -C : Adds support for botanical cultivars like Sarracenia flava 'Maxima' and graft-chimaeras like + Crataegomespilus

However, the manpage says

> -C, --cultivar          include cultivar epithets and graft-chimeras in normalized and canonical outputs

So, the README should be changed to `--cultivar` from `--cultivars`

version: v1.7.4
build:   2023-08-22_18:14:39UTC

**Comment by dimus** [comment]
Thank you for spotting this @joelnitta
