### ISSUE TITLE
Second year in name replaces first

### ISSUE THREAD

**Issue by jar398** [gnames/gnparser#256]
I don't know the right answer but to my eye the gnparser output looks wrong, because the input does not imply the existence of any publication by Hombrot and Jacquinot from the year 2020.  This is from the March 2021 version of the GBIF backbone (id 9704685) and version 1.6.7 of gnparser.

```
gnparser "Lobodon (Hombrot & Jacquinot, 1842), 2020"
Id,Verbatim,Cardinality,CanonicalStem,CanonicalSimple,CanonicalFull,Authorship,Year,Quality
449d5241-186f-5b1c-af6a-ec8786108fba,"Lobodon (Hombrot & Jacquinot, 1842), 2020",1,Lobodon,Lobodon,Lobodon,(Hombrot & Jacquinot 2020),2020,2
```

**Comment by dimus** [comment]
Sorry @jar398, just noticed this ticket. It is not a well-formed name, so I think also quality `2` should be changed to `4`. And yes, normalizer did not do a good job here. Marking it as a bug.
