### ISSUE TITLE
`Crisia romanica Zágoršek` does not parse correctly

### ISSUE THREAD

**Issue by dimus** [gnames/gnparser#259]
@LocoDelAssembly found that `Crisia romanica Zágoršek` does not recognize the author.
The reason is the `š`, a letter combined from `s` character and the `diacritic` character. This is a problem for all characters created this way.

**Comment by LocoDelAssembly** [comment]
@dimus the example turns out it was partially tweaked already. The "á" should actually be "á".

Actual name is `Crisia romanica Zágoršek Silye & Szabó 2008`.

**Comment by dimus** [comment]
Thanks @LocoDelAssembly, this is almost as a nasty problem as inserting cyrillic letters into the name (also happens). I wonder if it makes sense to normalize all strings before parsing (https://unicode.org/reports/tr15/)
