### ISSUE TITLE
More names with problematic epithets: complex, spec, do

### ISSUE THREAD

**Issue by KatjaSchulz** [gnames/gnparser#263]
These are all names from the Catalogue of Life (see links), and they currently get parsed incorrectly.

Valid/accepted:

[Aleuroclava complex Singh, 1931](https://www.catalogueoflife.org/data/taxon/BQBD)
[Allawrencius complex Lawrence, 1953](https://www.catalogueoflife.org/data/taxon/BTFQ)
[Cicada complex Walker, 1850](https://www.catalogueoflife.org/data/taxon/V5KG)
[Dichostasia complex Yochelson, 1956](https://www.catalogueoflife.org/data/taxon/B22NL)
[Dischidia complex Griff.](https://www.catalogueoflife.org/data/taxon/6CZ3H)
[Ecnomus complex Mosely, 1932](https://www.catalogueoflife.org/data/taxon/38NL8)
[Fusinus pauciliratus complex M. A. Snyder, 2000](https://www.catalogueoflife.org/data/taxon/7GSQ5)
[Gonatobotrys complex Jane Walker & Minter](https://www.catalogueoflife.org/data/taxon/6KPV4)
[Heizmannia (Heizmannia) complex (Theobald, 1910)](https://www.catalogueoflife.org/data/taxon/8C9GC)
[Oecetis complex Hwang, 1957](https://www.catalogueoflife.org/data/taxon/6SHYM)
[Oedipina complex (Dunn, 1924)](https://www.catalogueoflife.org/data/taxon/6SJLM)
[Paradimorphoceras complex (Moore, 1939)](https://www.catalogueoflife.org/data/taxon/4CTF5)
[Plectrocnemia complex Hwang, 1958](https://www.catalogueoflife.org/data/taxon/4K57H)
[Sceliphron fossuliferum complex Kohl, 1918](https://www.catalogueoflife.org/data/taxon/5L2XZ)
[Scopaeus (Scopaeus) complex Sharp, 1874](https://www.catalogueoflife.org/data/taxon/9QPNS)
[Sigipinius complex Golovatch, 2013](https://www.catalogueoflife.org/data/taxon/6YNWN)
[Stegosoladidus complex Berge, 2001](https://www.catalogueoflife.org/data/taxon/4ZP9G)
[Trisephena complex Medler, 1990](https://www.catalogueoflife.org/data/taxon/7D6NF)

[Castelnaudia spec (Darlington, 1962)](https://www.catalogueoflife.org/data/taxon/RPBN)
[Hemicloeina spec Platnick, 2002](https://www.catalogueoflife.org/data/taxon/3KMMR)
[Notozomus spec (Harvey, 1992)](https://www.catalogueoflife.org/data/taxon/47ZDD)

[Parentia do Bickel, 2002](https://www.catalogueoflife.org/data/taxon/4DKWR)
[Tetramorium do Forel, 1914](https://www.catalogueoflife.org/data/taxon/55PLD)
[Odontella do Najt, J & Weiner, WM in Najt, J & Matile, L, 1997](https://www.catalogueoflife.org/data/taxon/8ZNRW)

Synonyms:

[Bolbodeomyia complex Theobald, 1910](https://www.catalogueoflife.org/data/taxon/8B7RQ)
[Dimorphoceras complex (Moore, 1939)](https://www.catalogueoflife.org/data/taxon/367HX)
[Fusinus complex M. A. Snyder, 2000](https://www.catalogueoflife.org/data/taxon/6JTS5)
[Libystica complex Holland, 1894](https://www.catalogueoflife.org/data/taxon/94TN2)
[Ochodaeus complex LeConte, 1868](https://www.catalogueoflife.org/data/taxon/6SF2T)
[Oedipus complex Dunn, 1924](https://www.catalogueoflife.org/data/taxon/48WKM)
[Oedopinola complex (Dunn, 1924)](https://www.catalogueoflife.org/data/taxon/48WSQ)
[Phyllospongia complex de Laubenfels, 1954](https://www.catalogueoflife.org/data/taxon/6VG2B)
[Rubus complex L. H. Bailey](https://www.catalogueoflife.org/data/taxon/4TJT9)
[Sceliphron complex Kohl, 1918](https://www.catalogueoflife.org/data/taxon/4V4RQ)
[Scopaeus complex Sharp, 1874](https://www.catalogueoflife.org/data/taxon/9QPNT)
[Tetracis complex Sharp, 1874](https://www.catalogueoflife.org/data/taxon/9R5VM)

[Trichosternus spec Darlington, 1962](https://www.catalogueoflife.org/data/taxon/58KV7)

**Comment by dimus** [comment]
thank you @KatjaSchulz, I'll add them to the exceptions
