### ISSUE TITLE
Named hybrids have the authorship included in the parsed species field

### ISSUE THREAD

**Issue by gdower** [gnames/gnparser#266]
For named hybrids, the authorship gets included in the parsed species field:

`"species": "cus L."`
https://parser.globalnames.org/?format=html&names=Aus+x+cus+L.&with_details=on

In comparison, parsing works as expected for hybrid formulas:

```
"species": "bus",
...
"species": "cus",
...
```
https://parser.globalnames.org/?format=html&names=Aus+bus+L.+x+Aus+cus+L.&with_details=on

**Comment by dimus** [comment]
Definitely a bug
