### ISSUE TITLE
Adding nomenclatural code as a flag

### ISSUE THREAD

**Issue by gdower** [gnames/gnparser#267]
As a GNParser user, it would be useful to indicate the nomenclatural code that gnparser should use. For example, in botanical mode GNParser would interpret and normalize scientific names and authorships according to IPNI's style.

Some examples IPNI vs the current GNparser normalized form:

IPNI: [Glaphyropteris simulans (Ching) H.Ito in Nakai & Honda](https://www.ipni.org/n/17394290-1)
GNp: [Glaphyropteris simulans (Ching) H. Ito ex Nakai & Honda](https://parser.globalnames.org/?format=html&names=Glaphyropteris+simulans+%28Ching%29+H.Ito+in+Nakai+%26+Honda&with_details=on)

IPNI: [Glaphyropteris (Fée) C.Presl ex Fée](https://www.ipni.org/n/17394180-1)
GNp: [Glaphyropteris (Fee) C. Presl ex Fée](https://parser.globalnames.org/?format=html&names=Glaphyropteris+%28F%C3%A9e%29+C.Presl+ex+F%C3%A9e&with_details=on)

IPNI: [Hemionitis pinnata Hook.f.](https://www.ipni.org/n/120064-2)
GNp: [Hemionitis pinnata Hook. fil.](https://parser.globalnames.org/?format=html&names=Hemionitis+pinnata+Hook.f.&with_details=on)

IPNI: [Dacrycarpus (Endl.) de Laub.](https://www.ipni.org/n/32173-1)
GNp: [Dacrycarpus subgen. Endl. de Laub.](https://parser.globalnames.org/?format=json&names=Dacrycarpus%20(Endl.)%20de%20Laub.&with_details=on)

So it would mainly be taking out the space with C. Presl as C.Presl, not normalizing filius to fil. (e.g., Hook. fil. as Hook.f.), fixing the ex/in issue, and handling genus combination authorships. I'm not sure why GNp normalizes Fée to Fee in the original authorship. For handling genus combination authorships, often I know the rank with high confidence and could provide that as a parameter like &rank=genus to help GNp interpret it correctly although that might only work when parsing 1 name at a time.

It might still be useful to have an independent flag for f. to fil. normalization. While IPNI uses the f. for filius, normalizing to fil. could still be useful in some cases to disambiguate from f. for forma.

**Comment by dimus** [comment]
@gdower I did not close the ticket, please close it if all works the way you expect, or write here if something is not right.
