### ISSUE TITLE
Add explanation for canonical form different uses for 'simple' and 'full' canonical forms.

### ISSUE THREAD

**Issue by dimus** [gnames/gnparser#44]
created by @dimus at https://gitlab.com/gogna/gnparser/-/issues/44

Related to https://github.com/GlobalNamesArchitecture/gnparser/issues/480

**Comment by abubelinha** [comment]
Not an issue but a question.  I want to correctly explain the origin of the term "canonical name" before using it in a text.
AFAIK, canonical means "according to laws or rules". But here the word is used in other sense (just obviating the authorship, year and other annotations ... and keeping latin name and epithets).

A ["canon*" word search](https://www.iapt-taxon.org/nomen/search.html?zoom_query=canon*&x=0&y=0&zoom_sort=0) of IAPT nomenclatural code, returns only one entry. And it refers to [religious canonizations](https://en.wikipedia.org/wiki/Canon_law) of authors (see art. [60C.4.d](https://www.iapt-taxon.org/nomen/pages/main/art_60.html?zoom_highlight=canon*)).

So what is the origin of the expression "canonical form/name" applied in the sense used here?
- I see it used in [TNRS](https://dx.doi.org/10.1186/1471-2105-14-16) (2013) for the first time.
- [gnparser](https://doi.org/10.1186/s12859-017-1663-3) (2017) paper explains a little more (_We refer to the form of the scientific name without authority or annotations as the “canonical form”_). 
- It is also defined in [globalnames glossary](https://globalnames.org/docs/glossary/#canonical-name): "_The canonical name is comprised of the latinized elements of a scientific name._"

But none of them is citing where the term came from (I mean, who made the decision of calling that "canonical name" for the first time). 
Was the term applied in this sense to biological names, somewhere else before that TNRS paper?

Thanks!

**Comment by dimus** [comment]
I am not sure who came with the `canonical name` term first. Paddy Patterson defines it like

Canonicalization. Canonicalization, the removal of spurious elements from name-strings
to leave the Latinized elements

in

Patterson D, Mozzherin D, Shorthouse D, Thessen A (2016) Challenges with using names to link digital biodiversity information. Biodiversity Data Journal 4: e8080.
doi:10.3897/BDJ.4.e8080
