### ISSUE TITLE
Parse nasty names with ambivalent specific epithets

### ISSUE THREAD

**Issue by dimus** [gnames/gnparser#53]
created by @dimus at https://gitlab.com/gogna/gnparser/-/issues/53

@diatomsRcool, @KatjaSchulz and @joelnitta found the following names:

```
Acrostichum nudum
Adiantum nudum
Africanthion nudum
Agathidium nudum
Aphaniosoma nudum
Aspidium nudum
Athyrium nudum
Bembidion satellites
Blechnum nudum
Bolivina prion
Boreophilia nomensis
Bottaria nudum
Erateina satellites
Gnathopleustes den
Ithomeis satellites
Lycopodium nudum
Navicula bacterium
Nephodia satellites
Nephrodium nudum
Paralvinella dela
Phelodon nomene
Polypodium nudum
Polystichum nudum
Psilotum nudum
Ruteloryctes bis
Selenops ab
Tortolena dela
Trachyphloeosoma nudum
Xestia cfuscum
Zodarion van
```

We need to double check that they are 'real' and whitelist the real ones in rules O.o

**Comment by KatjaSchulz** [comment]
Hi Dima,

Here are a few more names for your whitelist.  These are all from the current version of the Catalogue of Life (COL-2021-06-10):

Navicula bacterium (diatom)
Xestia cfuscum (moth)
Bolivina prion  (foraminifer)
Bembidion satellites (beetle)
Erateina satellites (moth)
Ithomeis satellites (butterfly)
Nephodia satellites (moth)

Also, names don’t get parsed if the generic name is too short, but there are a few two letter genera:

Do holotrichius (beetle)
Oo spinosum (arachnid)
Nu aakhu (annelid)

Maybe these could get whitelisted, too?

**Comment by dimus** [comment]
@KatjaSchulz thanks for more 'nasty' names, I am going to bump priority up for this issue

**Comment by dimus** [comment]
Oh, I thought I have all two-letter genera accounted for:

TwoLetterGenus <- ('Ca' / 'Ea' / 'Ge' / 'Ia' / 'Io' / 'Ix' / 'Lo' / 'Oa' /
  'Ra' / 'Ty' / 'Ua' / 'Aa' / 'Ja' / 'Zu' / 'La' / 'Qu' / 'As' / 'Ba')
