### ISSUE TITLE
Make a homebrew package for gnparser

### ISSUE THREAD

**Issue by dimus** [gnames/gnparser#92]
created by @dimus at https://gitlab.com/gogna/gnparser/-/issues/92

**Comment by dimus** [comment]
@sckott quite a few changes happened with gnparser. 
- I moved it to github
- It is now upgraded to versions 1.x (some with someincompatibilities with 0.x
- I did create formular for mac/linux, however it is rejected by brew scripts because the repo does not have enough stars, forks and watchers:
https://github.com/Homebrew/homebrew-core/pull/69451

Changes between 0.x and 1.x are here: https://github.com/gnames/gnparser/wiki/Changes-in-v1.0.0

**Comment by sckott** [comment]
Thanks for the update!

**Comment by sckott** [comment]
@dimus what happened to the debug functionality? I had a function in the R client that did `-f debug` - that seems to be gone, or is it still there somewhere?  I don't care one way or the other, just that I have it in the R client and need to know if I remove that functionality or not

**Comment by dimus** [comment]
@sckott I decided to remove it as it really was only for development

> @dimus what happened to the debug functionality? I had a function in the R client that did `-f debug` - that seems to be gone, or is it still there somewhere? I don't care one way or the other, just that I have it in the R client and need to know if I remove that functionality or not

**Comment by dimus** [comment]
I also removed gRPC from the package, because protobuf API was changing a lot and for users it was hard to compile gnparser. I am planning to remove gRPC dependency from all the packages

**Comment by sckott** [comment]
Okay, thanks
